### ISSUE TITLE
Software layer/Build nodes documentation out of date

### ISSUE THREAD

**Issue by Neves-P** [EESSI/docs#112]
The documentation at the [Build nodes](http://www.eessi.io/docs/software_layer/build_nodes/) page is out of date. Many of the installation steps have been moved to `build_container.sh` and some of the hard-coded paths have changed since the documentation was written.

Since new software installation is now achieved mainly through the bot, perhaps this page could be revised with up to date information for the purpose of manually debugging cases that require a more manual inspection of each step.

**Comment by laraPPr** [comment]
see https://gitlab.com/eessi/support/-/issues/58
